name: Terraform CI/CD Pipeline For Deploying AWS Resources
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./terraform-vpc-eks
        
      - name: Destroy infra 
        if: github.event_name == 'pull_request'
        run: terraform destroy --auto-approve
        working-directory: ./terraform-vpc-eks 
